data_paths:
  train_dir: "/home/prasadd/Desktop/superres/dataset/train/DIV2K_train_HR" # path of training HR image files
  valid_dir: "/home/prasadd/Desktop/superres/dataset/valid/DIV2K_valid_HR" # path of validation HR image files
  test_dir: "/home/prasadd/Desktop/superres/dataset/test/" # path of testing benchmark datasets

degradation_params:
  scale: 4  # [2, 3, 4]
  mode: "bicubic" # [bicubic, s-fold]
  kernel_size: 20
  blur_type: "aniso_gaussian" # [iso_gaussian, aniso_gaussian]
  sig: 2.6
  sig_min: 0.2
  sig_max: 4.0
  lambda_1: 0.2
  lambda_2: 4.0
  theta: 0
  lambda_min: 0.2
  lambda_max: 4.0
  noise: 0.0

training_params:
  learning_rate: 0.001
  mini_batch_size: 64
  epochs: 500
  patience: 10